package controller;

import helper.AppointmentsDAO;
import helper.DatabaseHelper;
import helper.UserDAO;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import model.Appointments;
import utils.LocalizationUtil;
import utils.SceneChanger;
import utils.UIUtils;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

public class LoginController implements Initializable {
    @FXML
    private TextField usernameField;

    @FXML
    private PasswordField passwordField;

    @FXML
    private Button loginButton;

    @FXML
    private Button cancelButton;

    @FXML
    private Label loginLabel;

    @FXML
    private Label locationText;


    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        // Setup Locale and determine user's language preference
        LocalizationUtil.setupLocale();

        // Update the labels and buttons with the appropriate language
        if (LocalizationUtil.isFrench()) {
            loginLabel.setText(LocalizationUtil.getLocalizedString("login"));
            loginButton.setText(LocalizationUtil.getLocalizedString("loginButton"));
            cancelButton.setText(LocalizationUtil.getLocalizedString("cancelButton"));
        } else {
            loginLabel.setText("Login");
            loginButton.setText("Login");
            cancelButton.setText("Exit");
        }

        // Set the user's location in the location field
        locationText.setText(LocalizationUtil.getUserLocation());
    }


    @FXML
    protected void onCancelButtonClick() {
        // Close the application when the "Exit" button is clicked
        Platform.exit();
    }

    /**
     * Event handler for the login button click. This method is invoked when the login button is clicked.
     * It processes the user's login attempt, validates the credentials, and performs relevant actions upon success or failure.
     *
     * @param event The action event generated by the login button click.
     */
    @FXML
    protected void onLoginButtonClick(javafx.event.ActionEvent event) {
        String username = usernameField.getText();
        String password = passwordField.getText();

        if (UserDAO.validateLogin(username, password)) {
            UIUtils.showInfoAlert(LocalizationUtil.getLocalizedString("successLogin"));

            // Check for upcoming appointments after successful login
            List<Appointments> upcomingAppointments = AppointmentsDAO.getUpcomingAppointmentsWithin15Minutes();

            if (!upcomingAppointments.isEmpty()) {
                StringBuilder alertMessage = new StringBuilder("You have the following appointments within the next 15 minutes:\n\n");
                for (Appointments appointment : upcomingAppointments) {
                    alertMessage.append("Appointment ID: ").append(appointment.getId())
                            .append(", Date: ").append(appointment.getStartDateTime().toLocalDate())
                            .append(", Time: ").append(appointment.getStartDateTime().toLocalTime())
                            .append("\n");
                }
                UIUtils.showInfoAlert(alertMessage.toString());
            } else {
                UIUtils.showInfoAlert("You have no upcoming appointments in the next 15 minutes.");
            }

            try {
                // Update this path if it's located elsewhere
                String fxmlPath = "/view/MainScreen.fxml";
                SceneChanger.changeScene(event, fxmlPath);
            } catch (IOException e) {
                UIUtils.showErrorAlert(LocalizationUtil.getLocalizedString("errorChangingScene"));
            }
        } else {
            UIUtils.showErrorAlert(LocalizationUtil.getLocalizedString("invalidCredentials"));
        }
    }



}
